### ISSUE TITLE
Roadmap ... Ideas ...

### ISSUE THREAD

**Issue by pergolafabio** [pergolafabio/Hikvision-Addons#42]
- [X] Define multiple doorstations
- [ ] Create camera entity based on isapi or rtsp url
- [ ] Two way audio maybe with webrtc card => https://github.com/pergolafabio/Hikvision-Addons/issues/50
- [x] More events based on input/output relays  
- [X] use stdin service to send ISAPI commands, like reboot
- [ ] Key/badge management, like temp access for specific people allow door access

**Comment by giacomitti** [comment]
Act as a Media Player, so with the Two Way Audio without SIP #50 you can play direct on the doorstation.

**Comment by pergolafabio** [comment]
Found an interesting one, Hikvision mqtt with two way audio

https://github.com/electric-monk/mqtt-hikvision/

**Comment by fabioz23** [comment]
I mean other doorphone products manufactured from other chinese CCTV brands like Dahua, TVT, etc.

On which platform i must reach you? I've tried on gitter but that username doesn't exist. Yestarday I've found you on Discord and I wrote some msgs.

**Comment by pergolafabio** [comment]
ahh, well this addon is specific for Hikvision, since its based on Hikvision SDK
I just have 1 device, it was for personal use and just shared it for other users using HA :-)

yeah, discord, but i dont remember messages from you  yesterday ? :-) whats your username on discord?

**Comment by fabioz23** [comment]
I'm writing now with my github bound account (fabioz23)

**Comment by pergolafabio** [comment]
hmm, then you must be speaking to someone else , i dont see any pm on discord :-)

**Comment by fabioz23** [comment]
:-)) maybe

My user is fabioz23#3500
Can you ping me back pls? 

I cannot found a user with "fabiopergola", i've found only "Pergola Fabio#4649".

**Comment by pergolafabio** [comment]
usefull for maybe an mqtt camera:

https://github.com/robmarkcole/mqtt-camera-streamer

I think we need to define the mqtt camera entity manually first in HA, since https://github.com/unixorn/ha-mqtt-discoverable , doesnt have support for it?
